### ISSUE TITLE
Autocomplete needs shortkey that isn't widely used for other purposes in text editing

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#100]
ctrl+a is not the best choice

**Comment by valterss** [comment]
Varbūt var izmanto Ctr+Enter? Tā ir arī SDL Trados noklusētā taustiņkombinācija

**Comment by YourLittleHelper** [comment]
@valterss Ctrl+Enter šobrīd jau ir apstiprināt segmentu.

**Comment by valterss** [comment]
@YourLittleHelper, sorry, pārpratu "autocomplete" :)

**Comment by YourLittleHelper** [comment]
Ctrl + A is no more, Tab selects autocomplete record.
