### ISSUE TITLE
Can't add same document to the list

### ISSUE THREAD

**Issue by valentinsk** [tilde-nlp/MateCat#105]
LV-ENG language pair is selected ->add document test.docx ->analyze
test.docx info is showed

I realized that wrong language pair is selected, changed lang.pair to ENG-LV -> upload doc, selected same test.docx, nothing happens
if file with different name selected, document upload is working

chrome browser

**Comment by bertab** [comment]
reopening issue. Adding the same file > the Analyze button doesn't appear [it works in some cases, i can upload the same doc without problems a few times, but then]
![image](https://user-images.githubusercontent.com/39264287/49566096-23da7300-f932-11e8-8cd2-82dfb3fa40ac.png)

**Comment by YourLittleHelper** [comment]
Seems fixed in hugotest.
