### ISSUE TITLE
Chrome: document.registerElement is deprecated and will be removed in M73, around March 2019

### ISSUE THREAD

**Issue by valterss** [tilde-nlp/MateCat#113]
![image](https://user-images.githubusercontent.com/1871951/47903640-a03dea00-de8c-11e8-9d13-b5a5c550bd44.png)

**Comment by valterss** [comment]
![image](https://user-images.githubusercontent.com/1871951/47903529-84d2df00-de8c-11e8-8b14-3b9126a920bf.png)

**Comment by makulatura** [comment]
This method is deprecated and also works only in chrome, so this issue should be addressed accordingly.
