### ISSUE TITLE
"Tulkot" button link disappears from the document list

### ISSUE THREAD

**Issue by valterss** [tilde-nlp/MateCat#114]
1) Upload quite a large document without pretranslate. "Tulkot" button is there.
![image](https://user-images.githubusercontent.com/1871951/47904915-7b4a7680-de8e-11e8-9747-89238555f81c.png)
2) Come back later or refresh the page and the "Tulkot" button together with other action buttons are gone
![image](https://user-images.githubusercontent.com/1871951/47905135-04fa4400-de8f-11e8-86b8-ac82125e5e35.png)

**Comment by YourLittleHelper** [comment]
Moved to tfs.
