### ISSUE TITLE
MT dropdown has 2 down carrets

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#115]
![image](https://user-images.githubusercontent.com/39264287/47992089-a0d8b980-e0f4-11e8-9c94-6016fc53d78e.png)

**Comment by bertab** [comment]
//in both views

**Comment by ArtursOrinskis** [comment]
@valterss bija uzdevums pārveidot sistēmu dropdownu par multiselectu ar meklēšanu? tur pašlaik ir divi elementi kopā samiksēti, derētu nomainīt uz pilnīgi custom vai pilnīgi bootstrap dropdownu.
