### ISSUE TITLE
Duplicating pretranslate options in an open document

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#116]
![image](https://user-images.githubusercontent.com/39264287/47992637-0c6f5680-e0f6-11e8-8dd5-ac91a3eab3e5.png)
and
![image](https://user-images.githubusercontent.com/39264287/47992645-13966480-e0f6-11e8-82ae-73e42bdeb4cc.png)

**Comment by YourLittleHelper** [comment]
@bertab Settings panel controls what happens when new files are analyzed, whether it should be pretranslated first time.
Priekštulkot dropdown works only in currently opened file and can be clicked (read: file can be pretranslated) unlimited times.

**Comment by bertab** [comment]
Was gonna ask if you just haven't removed them yet (as they serve no purpose when opened FROM the opened document) or reworked to function as the pretranslate menu does.

(in an open document) The problem is that since the Settings are right next to other menus, they don't come off as something global, but rather seem to open something related to this opened document. If the only reason for them to be there was to be able to change/view TM's then the pretranslate options don't serve any purpose and seem confusing
