### ISSUE TITLE
Concordance search lacks match %

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#118]

**Comment by YourLittleHelper** [comment]
@bertab During meeting last week I was told not to show percents for concordance, just like here https://hugotest.tilde.lv/lv/CorpusSearch?corpusId=c-b14e6fa7-d961-44e6-a54f-022417c02946&language=lv&query=likums&view=rows&page=1#result

**Comment by bertab** [comment]
@YourLittleHelper OK, cool. I guess we leave this one open. I'll remove assignment

**Comment by YourLittleHelper** [comment]
% match is not necessary for concordance.
