### ISSUE TITLE
comment badge/counter should disappear/change when the comments get resolved

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#17]
at the moment the badge outputs the number of total comments, regardless if they are resolved or not, since it looks like a notification badge it should output only the unresolved ones. 

(I don't see a reason to have the unresolved count displayed at all, but if needed it could work as a number in parentheses leaving the badge for the unresolved)

**Comment by valterss** [comment]
Kopējo komentāru skaitu varam parādīt iekavās aiz komentāru taba: "Komentāri (2)", nerādot uzmanību pievērsošo dzelteno apli.

**Comment by YourLittleHelper** [comment]
Moved to tfs.
