### ISSUE TITLE
"404 - Team not found in user memberships" on GetProjects

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#22]
`{"errors":[{"code":404,"message":"Team not found in user memberships"}],"data":[]}`

the previous request seems to have everything correct:
`{"user":{"uid":1,"first_name":"tester","last_name":"jwt_user","email":"testerTilde@gmail.com:-:testerTilde@gmail.com","has_password":true},"connected_services":[],"metadata":null,"teams":[{"id":1,"name":"Personal","type":"personal","created_at":"2018-08-14T07:35:29+02:00","created_by":1,"members":[{"id":1,"id_team":1,"user":{"uid":1,"first_name":"tester","last_name":"jwt_user","email":"testerTilde@gmail.com:-:testerTilde@gmail.com","has_password":true},"projects":6}],"pending_invitations":[]}]}`

haven't found a repro scenario, just logging out/re-logging till it reappears

[visually the projects don't get loaded, newly uploaded files disappear into nothingness and there's pagination visible even though there is no list]

**Comment by YourLittleHelper** [comment]
Can't repoduce both locally and on https://hugotest.tilde.lv/lv/Translate/Cat#/
Hopefully moving to stateless api will also fix this issue.
