### ISSUE TITLE
Settings don't update user choice (Chrome)

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#28]
All is false > I set everything to True:
![image](https://user-images.githubusercontent.com/39264287/45012377-895f5080-b01f-11e8-903c-be079ec18802.png)

 and close settings > everything is back to false

If i open a document and get back to the settings screen the choices have not been updated, if i refresh the page they finally appear in checked state as should

**Comment by bertab** [comment]
OK, so they changed, but after a long time and I've zero idea what happened in between. (I had tried to logout before in hopes they'd get updated, but to no effect)

**Comment by bertab** [comment]
Now the "Fill wit (..)" are being updated, but the TM checkboxes still take time to change the state

**Comment by YourLittleHelper** [comment]
Can't reproduce both locally and on https://hugotest.tilde.lv/lv/Translate/Cat#/

**Comment by bertab** [comment]
I can still produce it (hugotest.tilde.lv) + Chrome:
![image](https://user-images.githubusercontent.com/39264287/47715044-3e407300-dc47-11e8-82c0-e2f698ce94cc.png)
>uncheck the write properties & close the settings
>open settings:
![image](https://user-images.githubusercontent.com/39264287/47715123-75af1f80-dc47-11e8-8cc2-747c9eb740b8.png)

**Comment by bertab** [comment]
Neither tm, nor pretranslate checkboxes update their state
enable/disable some checkboxes>close settings>open settings the checkboxes are ok> refresh page>same state as before checking in/ checking out
