### ISSUE TITLE
Can't pass tags with arrow keys (certain cases)

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#37]
Update (28.11.) There have been changes in this behavior, so I'm updating the issue
cursor can't pass tags:
(segment 5 - separator '|' between tags)
[lv_docx (1).docx](https://github.com/tilde-nlp/MateCat/files/2623605/lv_docx.1.docx)
![image](https://user-images.githubusercontent.com/39264287/49139700-2538e980-f2fb-11e8-9ac3-292e808ede99.png)
(segment 16 - can't pass backwards)
![image](https://user-images.githubusercontent.com/39264287/49140262-7bf2f300-f2fc-11e8-946b-2106bebe1582.png)

(segment 5 - ',' a comma before tag)
[formatting_ru.docx](https://github.com/tilde-nlp/MateCat/files/2623615/formatting_ru.docx)
![image](https://user-images.githubusercontent.com/39264287/49139920-a4c6b880-f2fb-11e8-8764-5ddfdbb8c15c.png)

(segment 21 - spaces between tags)
[Kopa_Nosaukumu_kapitalizācija.docx](https://github.com/tilde-nlp/MateCat/files/2623611/Kopa_Nosaukumu_kapitalizacija.docx)
![image](https://user-images.githubusercontent.com/39264287/49139973-c6c03b00-f2fb-11e8-958a-0c46ff565b4e.png)

**Comment by bertab** [comment]
![image](https://user-images.githubusercontent.com/39264287/45608257-8e2df680-ba5a-11e8-91a5-3507aa4b8308.png)

**Comment by YourLittleHelper** [comment]
Moved to tfs.
