### ISSUE TITLE
Pretranslate doesn't load document content without refreshing the page

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#49]
open the document -> pretranslate progress indicator is shown -> I have to reload the page for it to load content

**Comment by YourLittleHelper** [comment]
Can't reproduce. Pretranslate can take very long time to complete. Reloading page will show already pretranslated segments, but will interrupt pretranslation. Currently pretranslate timeout is 30 minutes. If requests ?action=pretranslate is still loading, pretranslating is still happening.

There are plans to create asynchronous worker for pretranslation, but for now it's synchronous.
