### ISSUE TITLE
Segment filtering works on tags and breaks the tag visual representation when highlighting

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#50]
I doubt it's beneficial for anyone to filter segments by tags and the visual change of the tagd when it gets highlighted might just seem confusing

![image](https://user-images.githubusercontent.com/39264287/45620723-7ec4a280-ba86-11e8-9b20-916f03c80ff4.png)

**Comment by YourLittleHelper** [comment]
Moved to tfs.
