### ISSUE TITLE
Non-Chrome browsers are missing alerts 

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#61]
FF/Edge -> Upload an unsupported file type -> no error is shown

**Comment by YourLittleHelper** [comment]
@bertab Can't reproduce on https://hugotest.tilde.lv/lv/Translate/Cat#/

**Comment by bertab** [comment]
Man ir aizdoma, ka Uldis salaboja kaut ko citu labojot, bet nebija nočekots
