### ISSUE TITLE
Fix the comment section paddings and input width

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#64]
Paddings, input field width, button placement (btn placement already has a separate bug for differences across browsers #11 )  
![image](https://user-images.githubusercontent.com/39264287/45733757-94eb7380-bbea-11e8-8ea5-6faf3ece50fd.png)

vs design:
![image](https://user-images.githubusercontent.com/39264287/45733876-04616300-bbeb-11e8-834c-c9d92e0aacda.png)

**Comment by bertab** [comment]
atstartpe starp "Komentāri" un atdalošo līniju

**Comment by makulatura** [comment]
uztaisīju mazāku
