### ISSUE TITLE
TM suggestions for tagged text - tag handling/copying (TM suggestions should be tagged just like MT)

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#66]
as it stands now it's impossible to insert tags, you can just copy them from source. 
If you copy a TM suggestion that has no tags there is no way to add tags into the text
![image](https://user-images.githubusercontent.com/39264287/45862672-7d8fc000-bd7b-11e8-96d5-372b3a9b60a3.png)

TM suggestions should be tagged just like MT

**Comment by valterss** [comment]
Ar tulkošanas atmiņas servisu un tagiem jāņem vērā sekojoša lieta:
- Tulkošanas atmiņas servisā apstiprinātie tulkojumi ir jāliek kā plaintext - gan source, gan target teksti bez tagiem
- Vaicājumus TM servisam jāveic ar tagiem un TM serviss pratīs ielikt tagus ieteikumā atbilstošajās vietās

**Comment by valterss** [comment]
Kādā kodējumā jānodod tagi - < vai &gt;?

**Comment by bertab** [comment]
It works:
![image](https://user-images.githubusercontent.com/39264287/47997164-970a8280-e103-11e8-9c84-aa10bef25af1.png)
But not always, example - 2 words one of them is bolded:
![image](https://user-images.githubusercontent.com/39264287/47997188-abe71600-e103-11e8-869f-13a7980bbf4c.png)

**Comment by YourLittleHelper** [comment]
@valterss What could be the cause of TM not inserting tags? Matecat api and front-end does as instructed, seems like there are some issue cases on TM side.
