### ISSUE TITLE
Pretranslate doesn't work from an open document

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#68]
pressing "Translate all with MT" or "Translate all with 100%" seems to start the process, but none of the segments get filled in the end
![image](https://user-images.githubusercontent.com/39264287/46064987-946a5400-c179-11e8-9498-dbe14cde662b.png)

**Comment by bertab** [comment]
With TM there are inconsistencies as to  what gets returned, so that might be part of the issue:
![image](https://user-images.githubusercontent.com/39264287/46076262-b7a2fc80-c195-11e8-84d8-1f819469254f.png)
then refreshing the page I sometimes get only the public TM results:
![image](https://user-images.githubusercontent.com/39264287/46076418-297b4600-c196-11e8-99a7-f3f32e9668d1.png)

**Comment by YourLittleHelper** [comment]
Problem found, fix pushed to code-merge branch.
Found issue where tag converter dies causing infinite suggestion loading, issue raised separately.
