### ISSUE TITLE
Target segments in a document sent from translation to matecat are empty

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#76]
![image](https://user-images.githubusercontent.com/39264287/46196926-ff9a5e80-c310-11e8-974c-997767e49f9c.png)

**Comment by valterss** [comment]
@YourLittleHelper vai ielādējot failu caur API, mēs varam norādīt, ka failu ir nepieciešams pretulkot ar MT?

**Comment by YourLittleHelper** [comment]
@valterss Jā, upload vaicājumam ir parametri tm_pretranslate, mt_pretranslate kur var norādīt 0/1 vērtības lai notiktu faila pretranslate.
