### ISSUE TITLE
Tagged segment empty after confirmation

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#78]
Copu source to target -> edit the text -> confirm -> it becomes green -> refresh page -> text is gone
![image](https://user-images.githubusercontent.com/39264287/46201331-8143b980-c31c-11e8-96b8-d109c5d7210b.png)

it has been sent to TM:
![image](https://user-images.githubusercontent.com/39264287/46201418-c667eb80-c31c-11e8-9f0e-0f66da20aa43.png)

**Comment by valterss** [comment]
Ar tulkošanas atmiņas servisu un tagiem jāņem vērā sekojoša lieta:
- Tulkošanas atmiņas servisā apstiprinātie tulkojumi ir jāliek kā plaintext - gan source, gan target teksti bez tagiem
- Vaicājumus TM servisam jāveic ar tagiem un TM serviss pratīs ielikt tagus ieteikumā atbilstošajās vietās

**Comment by YourLittleHelper** [comment]
@bertab Can't reproduce locally and on hugotest. If problem persists, please provide file being tested on.

@valterss Stripped tags when writing in memory. Encoding http query when asking for suggestions. Seems like it works ok.
Get query: tm/Public/segments?q=%C5%A0is+ir+%3Cg+id%3D%221%22%3Eteksts%3C%2Fg%3E&sourceLang=lv&targetLang=en&concordance=false

Is this fine?
