### ISSUE TITLE
IE 11 hangs on loading

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#8]
![image](https://user-images.githubusercontent.com/39264287/43879250-c5b77d2e-9bab-11e8-8aa7-7c7dd9ebe54a.png)

**Comment by ArtursOrinskis** [comment]
https://caniuse.com/#search=promise

IE nesuportē "Promise" objektus. Pamēģināšu integrēt kādu polyfill.

**Comment by ArtursOrinskis** [comment]
https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js der

**Comment by ArtursOrinskis** [comment]
ievilku skriptu pie mums lokāli, jo https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/ minēta open source licence. ar nākamo hugo būvējumu strādās
