### ISSUE TITLE
Vizuāli attēlot TM fuzzy match atšķirības

### ISSUE THREAD

**Issue by valterss** [tilde-nlp/MateCat#81]
Atšķirības tulkojumā, izcelt atšķirīgos vārdus

**Comment by valterss** [comment]
SDL piemērs
https://www.vertaalt.nu/file/Trados-studio-2017-review-uplift-fuzzy-repair-1.jpg

**Comment by valterss** [comment]
Jāpārdomā risinājums, jo arī SDL tradosā netiek attēlotas atšķirības Hugo TM

**Comment by YourLittleHelper** [comment]
Moved to tfs.
