### ISSUE TITLE
Terminu un sinonīmu meklēšana

### ISSUE THREAD

**Issue by valterss** [tilde-nlp/MateCat#83]
- [x] sinonīmu links [Valters]

**Comment by valterss** [comment]
Sinonīmu links: https://hugokisc.tilde.lv/en?text=tent&systemid=smt-adbbe8ef-d0bb-484b-8d43-2ca67aa18e41

Ir gan problēma mūsu pusē automātiski ielādēt sinonīmu, bet adrese ir pareiza.

**Comment by artursvasilevskis** [comment]
according to design: https://app.zeplin.io/project/5af32bb773913cf64dc45c68/screen/5bb9e10661d56308d7533e72

**Comment by YourLittleHelper** [comment]
Added param to config.ini that needs to be added to deployment. Must provide link that can be concatenated with searched synonym. 

SYNONYM_BASE_URL = " https://hugokisc.tilde.lv/en?systemid=smt-adbbe8ef-d0bb-484b-8d43-2ca67aa18e41&text="

**Comment by valterss** [comment]
SystemID no mašīntulka uzstādījumiem, atverot vārdnīcas šķirkli
