### ISSUE TITLE
New line within segment is displayed as "[..]Valsts ##$_0A$##prezidents [..]" instead of breaking it in two lines

### ISSUE THREAD

**Issue by valterss** [tilde-nlp/MateCat#86]
![image](https://user-images.githubusercontent.com/1871951/46394993-86757f80-c6f3-11e8-95bf-a7a3b878f028.png)
Test document
[Krimināllikums.docx](https://github.com/tilde-nlp/MateCat/files/2440941/Kriminallikums.docx)

**Comment by valterss** [comment]
Šī problēma ir arī citiem simboliem: Kad ielādē word dokumentu un vietās, kur ir spiests TAB taustiņš ir ķeburi.
![image](https://user-images.githubusercontent.com/1871951/47202243-4e25a080-d385-11e8-9f71-91d6abcb06fc.png)

**Comment by YourLittleHelper** [comment]
TAB: ##$_09$##

**Comment by YourLittleHelper** [comment]
Moved to tfs.
