### ISSUE TITLE
Edge segment formatting issues

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#9]
there are scroll arrows for each segment + an offset in every row:
![image](https://user-images.githubusercontent.com/39264287/43879706-e623b03a-9bad-11e8-82da-008a8a9a0f04.png)
And it has a bit of an offset in header for Edge/FF (can't check IE atm)
Edge:
![image](https://user-images.githubusercontent.com/39264287/43880113-b05a9a84-9baf-11e8-80ca-5298b489084f.png)
vs FF
![image](https://user-images.githubusercontent.com/39264287/43880141-ce4989e2-9baf-11e8-90cd-29c15d6e712c.png)

**Comment by YourLittleHelper** [comment]
Fixed.
