### ISSUE TITLE
Settings - TM 'write' property should not be checked by default

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#93]
- [x] Make memory write flag false by default

**Comment by bertab** [comment]
Even if you have the rights, it would be better to keep it unchecked, otherwise users with large tm lists will have to uncheck all of them. 
@valterss  Maybe we should add a "check/uncheck all" button

**Comment by YourLittleHelper** [comment]
Made write settings off by default.

@valterss We need to revise memory list design to be up to date, before we can add new checkboxes in this view.
